header ui issues, scroll issue fixed, profile icon inclick fixed
hlxsites/airindia pull request #100
Opened 2024-05-07 16:43 UTC by kalimuthu-a

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #84 

Test URLs:
- Before: https://main--airindia--hlxsites.hlx.live/in/en/book/special-offers/global-connectivity
- After: https://header-ui-issues--airindia--hlxsites.hlx.live/in/en/book/special-offers/global-connectivity

2024-05-08 12:14 UTC, sselvara requested changes

2024-05-08 12:14 UTC, sselvara commented on scripts/scripts.js
> +  await import('./utils/blockUtils.js');
can this import added immediately after loading the header and footer?

2024-05-09 05:36 UTC, kalimuthu-a commented on scripts/scripts.js
> +  await import('./utils/blockUtils.js');
Done Subash

2024-05-09 17:30 UTC, sselvara approved these changes

2024-05-09 17:32 UTC, merged