Fixes for header 2nd iterarion
hlxsites/airindia pull request #48
Opened 2024-02-06 16:58 UTC by kalimuthu-a

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #43 

Test URLs:
- Before: https://main--airindia--hlxsites.hlx.live/in/en/book/special-offers/global-connectivity
- After: https://signed-in-experience-2--airindia--hlxsites.hlx.live/in/en/book/special-offers/global-connectivity

2024-02-07 06:06 UTC, sselvara approved these changes

2024-02-07 06:10 UTC, sselvara commented
@kalimuthu-a I can see visual differences
Live:
<img width="1785" alt="image" src="https://github.com/hlxsites/airindia/assets/25244481/70d78cb3-136c-46fc-b5ca-19c45d08455d">
EDS:
<img width="1785" alt="image" src="https://github.com/hlxsites/airindia/assets/25244481/6933be51-4a01-4016-918f-161598843c37">

cc: @sdmcraft

2024-03-11 18:48 UTC, sselvara commented
> Not introduced in this PR but something to look at, the 2nd level menu items seems to vanish on smaller screens
> 
>  Screen.Recording.2024-02-08.at.2.50.37.PM.mov
@kalimuthu-a  this is still reproducible, one way to reproduce is to open hamburger and open chat in sequence to see the overlap.

2024-03-11 19:04 UTC, sselvara requested changes
@kalimuthu-a issue https://github.com/hlxsites/airindia/pull/48#issuecomment-1931355785 still exists. please fix

2024-03-16 12:00 UTC, sdmcraft approved these changes

2024-03-18 05:20 UTC, sselvara approved these changes

2024-03-18 05:25 UTC, closed without merging