I 33 41
hlxsites/airindia pull request #50
Opened 2024-02-21 08:32 UTC by adobenitesh

Fix #33 #41 #42

Test URLs:
- Before: https://main--airindia--hlxsites.hlx.live/in/en/book/special-offers/global-connectivity
- After: https://i-33-41--airindia--hlxsites.hlx.live/in/en/book/special-offers/global-connectivity

2024-03-11 17:42 UTC, sselvara requested changes

2024-03-11 17:42 UTC, sselvara commented on blocks/header/header.js
> +    anchor.addEventListener('click', (e) => {
@adobenitesh will this not prevent the redirection if the anchor link has url?

2024-03-11 17:42 UTC, sselvara commented on blocks/header/header.js
> +    brandImg.forEach((img) => {
Can't we add Alt value in the doc?

2024-03-11 17:42 UTC, sselvara commented on styles/styles.css
> +  margin: 0;
Please double check the entire page and make sure that adding global changes has no impact in other places.

2024-04-10 11:47 UTC, dipratap commented
The footer docx needs changes for this PR, since main is dependent on footer docx changes, I haven't published the footer changes yet (they are saved though in the docx so if previewed they will appear) so the footer in https://i-33-41--airindia--hlxsites.hlx.live/in/en/book/special-offers/global-connectivity will appear distorted currently.

2024-04-10 12:24 UTC, sdmcraft reviewed
The footer looks broken. Not sure if its related to proposed changes but we should check 
![image](https://github.com/hlxsites/airindia/assets/1191451/204387c5-cc3c-4bb3-bbb9-5620fa33a53b)

2024-04-10 12:29 UTC, dipratap commented
> The footer looks broken. Not sure if its related to proposed changes but we should check

@sdmcraft Quoting my earlier comment here:

> The footer docx needs changes for this PR, since main is dependent on footer docx changes, I haven't published the footer changes yet (they are saved though in the docx so if previewed they will appear) so the footer in https://i-33-41--airindia--hlxsites.hlx.live/in/en/book/special-offers/global-connectivity will appear distorted currently.

I can preview and publish the changes in footer doc after which the footer will look correct, but it will distort the main one until these PR changes are merged. Your thoughts?

2024-04-11 11:32 UTC, dipratap commented
Temporary footer content docx added [here](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B753B48E5-2A98-4236-83F4-E38C13A11344%7D&file=footer.docx&action=default&mobileredirect=true) and used in this branch. The footer will appear correct now.

Original footer doc to be replaced with the temporary doc just before PR merge.

2024-04-18 07:19 UTC, dipratap commented
@sselvara Could you please review this?

2024-04-22 08:42 UTC, sselvara requested changes

2024-04-22 08:42 UTC, sselvara commented on blocks/header/header.js
> +    airIndiaIcon.setAttribute('alt', 'Air India');
can you please add these texts into placeholder file and fetch it to support i18n ?

2024-04-22 08:42 UTC, sselvara commented on blocks/header/header.js
> +    searchIcon.setAttribute('alt', 'Search icon');
can you please add these texts into placeholder file and fetch it to support i18n ?

2024-04-22 08:42 UTC, sselvara commented on blocks/booking/booking.css
> +    color: #70777B;
use color variables

2024-04-22 19:26 UTC, dipratap commented on blocks/header/header.js
> +    searchIcon.setAttribute('alt', 'Search icon');
done

2024-04-22 19:26 UTC, dipratap commented on blocks/booking/booking.css
> +    color: #70777B;
done

2024-04-22 19:33 UTC, dipratap commented
TODO post PR approval:
- Change below to use '/footer' in footer.js

`const footerPath = footerMeta.footer || '/drafts/divyansh/footer';`

- Update the main footer.docx file with draft changes.

2024-04-23 05:10 UTC, sselvara requested changes

2024-04-23 05:10 UTC, sselvara commented on blocks/booking/booking.js
> +    dateButton.setAttribute('aria-label', 'Date button');
Use placeholder file to fetch the text

2024-04-23 07:12 UTC, dipratap commented on blocks/booking/booking.js
> +    dateButton.setAttribute('aria-label', 'Date button');
Sure, done

2024-04-23 07:17 UTC, sselvara approved these changes

2024-04-23 07:27 UTC, merged